### ISSUE TITLE
Please update to work with core branch of pywikibot

### ISSUE THREAD

**Issue by mat-mo** [eranroz/hewiki-ReplaceBot#2]
and preferably, push the code to pywiki source. Thanks!

**Comment by eranroz** [comment]
The script is updated to core.

Regarding pushing it to pywiki source: The bot is very specific to hewiki. I'm not aware to other wikis with similar community maintained replacement list so for now I think it is better to keep it seperate

**Comment by eranroz** [comment]
I'm closing the ticket for core. Regarding merging it into pywikibot - see https://phabricator.wikimedia.org/T102317
